#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

echo "+++ Checking the following scipts"
find scripts -type f

echo "+++ Running shellcheck"
docker run \
  --rm \
  --interactive \
  --tty \
  --volume "${PWD}:/mnt" \
  koalaman/shellcheck:stable \
  scripts/*

echo "No problems"
