#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

environment="$1"

if [[ -z "${environment}" ]]; then
  echo "ERROR: no value for arg 1: environment"
  exit 1
fi

./scripts/terraform-init "${environment}"

echo "+++ Running Terraform plan for environment: ${environment}"
./scripts/terraform plan \
  --var-file "${environment}.tfvars" \
  --out "plans/${environment}"
