#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

./scripts/docker-build

echo "+++ Running Docker image"
docker run \
  --rm \
  --interactive \
  --tty \
  --volume "${PWD}/terraform:/mnt" \
  --workdir "/mnt" \
  --env AWS_ACCESS_KEY_ID \
  --env AWS_SECRET_ACCESS_KEY \
  servian-technical-challenge-tools:latest \
  terraform "$@"
