#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

docker run \
  --rm \
  --interactive \
  --tty \
  --volume "${PWD}:/mnt" \
  --workdir "/mnt" \
  --env AWS_ACCESS_KEY_ID \
  --env AWS_SECRET_ACCESS_KEY \
  --env AWS_DEFAULT_REGION \
  hashicorp/terraform:light \
  "$@"
